# Generated by Django 4.0.2 on 2022-02-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='operationID',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
