# Generated by Django 4.0.2 on 2022-02-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0008_alter_operation_timefinish_alter_operation_timestart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, to='redrock.status'),
        ),
    ]
