# Generated by Django 4.0.2 on 2022-02-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0009_alter_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(db_column='status_statusID', on_delete=django.db.models.deletion.CASCADE, to='redrock.status'),
        ),
    ]
