# Generated by Django 4.0.2 on 2022-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0014_employee_moveto_stow_alter_status_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='timeFinish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
