# Generated by Django 4.0.2 on 2022-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0016_subtask_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='operationID',
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
