# Generated by Django 4.0.2 on 2022-02-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redrock', '0011_alter_operation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='statusTitle',
        ),
    ]
