version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE='redrock'
      - MYSQL_USER='admin'
      - MYSQL_PASSWORD='o4yo8VCj'
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db