version: '3'

services:

  django:
    build: .
    container_name: django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - /tmp/app/mysqld:/run/mysqld
    networks:
     # - front-tier
       - back-tier
 
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=redrock
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - back-tier
networks:

 # front-tier:
 # name: frontend
    
  back-tier:
    name: backend
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
   

  